language: java
 
sudo: false
cache:
  directories:
  - $HOME/.m2
language: java
dist: trusty
jdk:
  - openjdk8
env:
  global:
    - SONATYPE_USERNAME=chicchiricco
    - secure: "OQaxP3bumnRPZG8+CWHdLn1TY/KmeVkS+Nl7sXuk6prQUdS9fZ6IYOkw/Q8ZR4E7vpc5ZmFXlDO+Bdi4BAaojeaqTK+6ATEFThSQqwHCVHqBz5Kx0kxJ4+h3/rKXTH7rouXcIsPkl0SrXQgGP1diMvOedsfSHPHI7NzaWblAql1sxdSCmH12f9kh2rhtKTKW46d9yuKMF1k3ehOixqfn3yUBQhVsBr5mOAk2hrLsFVk0MuBEK9Kgdrk3iic12oxeezZsrtlfkdOrtZHuXy6jl4sUCkmvruwPAmMFhenjwis2qooFLUEck+qrBw08PiZ+PfNqoCzf2S/kishew2zTdIVO+Hua+NCGKW3QW9Rb+8e6XvTDd0D62aE+XdfrIvuKL67oiLx9I6M9o40D9yRf+9WPZZr+/zFg/PQQliqU5g6t+165sXoocZ33f0ucqFdfmOP2TaKzt0Jd+pNX/32KFIRhgvHRMrEcQv5u5MjON6cd9ZWGu+TbkJEupT1V59WKANn+zOofmnq0dwpBvk+myIRYCR9BW60/SOcDf4zf5kGhPfHyKFBjJ+8aeXCNOgJkdRTI4UDtUky2rRNRcEsrE1Fry4WBBV3XyPhEQAqfA4Jw1cQ1CKghJ+GMpkjQ+hrkHMSKGYlertxDEYGepJ8fHN/putZO7O5+mjnxk6FvY7E="

after_success:
  - python .travis.addServer.py
  - mvn clean deploy --settings ~/.m2/mySettings.xml

notifications:
  email:
    - connid-dev@googlegroups.com
